---
## Author
author:
  name: Сидорова Александра Андреевна
  email: 1032256488@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Современные методы криптографии"
subtitle: "Анализ актуальных криптографических решений"
license: "CC BY"
---

# Введение 

Я хочу вам рассказать о совремнных методах криптографии - науке, лежащей в основе цифровой безопасности. В эпоху активного обмена данными она обеспечивает три основных аспекта защиты: конфиденциальность, целостность и аунтефикацию информации. 

# Цель работы

- Цель: изучить современные методы криптографии, показать как работает криптография функционирует в основе привычных технологий и почему её развитие критически важно для кибербезопасности. 
- Гипотеза: современные криптографические методы обеспечивают достаточный уровень защиты при правильном применении, но требуют адаптации к новым угрозам (квантовые вычисления и др.). 
- Задачи:
  - Изучить основные виды криптографии.
  - Проанализировать популярные алгоритмы (AES, RSA, ECC).
  - Рассмотреть примеры применения.
  - Оценить устойчивость к современным угрозам.
  - Обсудить направления развития.

# Актуальность криптографии сегодня. 
 
- Рост числа кибератак и утечек данных.
- Важность защиты информации в цифровую эпоху.
- Роль криптографии в обеспечении конфиденциальности, целостности и аутентификации данных.
- Случаии из жизни (утечка данных "СберЛогистики" 28 февраля 2023 года, были опубликованны данные о клиентах и сотрудниках сервиса. В октябре 2024 года хакерская группа BO team совершила атаку на систему арбитражных судов "Правосудие", хакеры получили доступ к судебным делам системы. 
- Тенденции: рост использования облачных сервисов, IoT, блокчейна — всё требует надёжной криптографии.

# Объект и предмет исследования

- Объект: современные методы криптографии.
- Предмет: принципы работы, области применения и эффективность современных криптографических алгоритмов.

# Практическая значимость работы

* Применение криптографии в:
  * Банковском секторе (защита транзакций).
  * Государственных системах (электронная подпись, защита персональных данных).
  * Корпоративной безопасности (VPN, шифрование данных).
  * Персональной безопасности (мессенджеры, облачные хранилища)

# Содержание исследования: методы и виды криптографии

## Методы криптографии 

- Шифрование 
- Стеганография 
- Кодирование 

### Шифрование 

Обратимое преобразование открытого текста на основе секретного алгоритма или ключа в шифрованный текст.

### Симметричное шифрование:

- Принцип: один ключ для шифрования и расшифровки.
- Алгоритмы: AES (Advanced Encryption Standard), DES, ГОСТ 34.12-2015.
- Плюсы: высокая скорость 
- Минусы: проблема распределения ключей.

### Асимметричное шифрование:

- Принцип: пара ключей (преобразование - открытый, дешифровка - закрытый).
- Алгоритмы: RSA, ECC (Elliptic Curve Cryptography).
- Плюсы: безопасная передача ключей.
- Минусы: низкая скорость.

### Хеш‑функции:

- Принцип: преобразование данных в фиксированный хеш ( не расшифровываются).
- Алгоритмы: SHA‑256, ГОСТ Р 34.11-2012.
- Применение: проверка целостности данных, пароли.

## Стеганография 

Суть этого метода скрыть данные среди открытой информации. Секретное сообщение внедряют в контейнер (информационный объект), который внешне не отличается от обычного файла. 

## Кодирование 

Кодирование представляет собой простой способ защиты сообщения путем использования различных наборов слов или символов, заменяющих слова или словосочетания в кодируемом сообщении. 

# Примеры современных алгоритмов

- AES: стандарт для симметричного шифровани, разбивается на блоки фиксированного размера (128 бит-16 байт)(используется в Wi‑Fi, VPN).
- RSA: асимметричный алгоритм для цифровой подписи и обмена ключами.(основан на модульной арифметике и свойствах простых чисел)
- ECC: альтернатива RSA с меньшими ключами и высокой скоростью (мобильные устройства, IoT). Использует математические свойства эллиптических кривых.
- SHA‑256: хеш‑функция для блокчейна и сертификатов.
- Постквантовые алгоритмы: NTRU, McEliece (устойчивость к квантовым атакам).

# Анализ и практическая значимость результатов

- Эффективность алгоритмов:
  - AES: быстрый, но требует безопасного обмена ключами.
  - RSA: надёжный, но медленный для больших объёмов данных.
  - ECC: оптимальный баланс для мобильных устройств.

- Устойчивость к атакам:
 - Симметричные:
AES (Advanced Encryption Standard) — международный стандарт блочного симметричного шифрования с длиной ключа 128, 192 или 256 бит. Считается стойким даже к мощным атакам. 
Большинство симметричных шифров предположительно устойчивы к атакам с помощью квантовых компьютеров, которые в теории представляют угрозу для асимметричных алгоритмов.  
  - Однако есть и уязвимости:
DES (Data Encryption Standard) — ключ длиной всего 56 бит, легко поддаётся брутфорс-атакам. Считается устаревшим для критически важных задач.
Слабое место симметричного шифрования— обмен ключом: поскольку для работы алгоритма ключ должен быть и у отправителя, и у получателя сообщения, его необходимо передать, но при передаче по незащищённым каналам его могут перехватить и использовать посторонние.
 - Асимметричные:
RSA (Rivest-Shamir-Adleman) — асимметричный алгоритм, основанный на сложности факторизации больших чисел. Экспоненциальная функция усиливает криптографическую стойкость алгоритма за счёт включения двух операций — возведения в степень и вычисления по модулю. Это делает алгоритм устойчивым к аналитическим атакам и попыткам восстановления исходного сообщения даже при знании части ключей или промежуточных данных.
ECC (Elliptic Curve Cryptography) — асимметричный алгоритм, основанный на эллиптических кривых. Обеспечивает ту же безопасность, что и RSA, но с более короткими ключами (например, 256 бит вместо 2048 бит). 
 - Однако есть и уязвимости:
Повторное использование открытого ключа — одна из наиболее критичных уязвимостей схем асимметричного шифрования, приводящая к снижению их стойкости. Злоумышленник может подделать или заменить открытый ключ, и, если система не умеет корректно проверять его подлинность, данные, шифруемые таким ключом, окажутся под угрозой.
Неправильная генерация параметров в ECC — может привести к уязвимости перед атаками, при которой злоумышленник подсовывает «плохую» точку на кривой и получает доступ к приватному ключу.

 - Угроза квантовых компьютеров: RSA и ECC уязвимы, постквантовые методы — решение.

## Постквантовые методы шифрования 

Постквантовые методы шифрования(постквантовая криптография) — это алгоритмы, устойчивые к атакам квантовых компьютеров. В отличие от классической криптографии, основанной на сложности факторизации больших чисел (RSA) или логарифмов на эллиптических кривых (ECC), постквантовые алгоритмы строятся на математических задачах, которые остаются сложными даже для квантовых вычислений. 
Стойкость постквантового шифрования гарантируется математическими доказательствами секретности каждого из алгоритмов — все они проверяются мировым научным математическим сообществом.

# Рекомендации  

- Использовать гибридные схемы (AES + RSA).
- Внедрять ECC для  мобильных приложений.
- Готовиться к переходу на постквантовую криптографию.

# Общее заключение и выводы

- Современные методы криптографии обеспечивают высокий уровень защиты данных при грамотном применении.
- Симметричные алгоритмы подходят для шифрования больших объёмов, асимметричные — для обмена ключами и подписи.
- Постквантовая криптография — ключевое направление будущего.
- Необходимо следить за развитием технологий и адаптировать системы безопасности. 
- Криптография остаётся фундаментом кибербезопасности в цифровую эпоху.

# Список литературы{.unnumbered}

::: {#refs}
:::

@online{yandex_cryptography,
  title     = {Что такое криптография и как она стала частью нашей жизни},
  author    = {Яндекс Практикум},
  year      = {2023},
  url       = {https://practicum.yandex.ru/blog/chto-takoe-kriptografiya/},
  urldate   = {2024-04-15},
  language  = {russian},
  howpublished = {Электронный ресурс}
}

@online{kaspersky_cryptography,
  title     = {Криптография: что это такое, виды и применение},
  author    = {Kaspersky},
  year      = {2023},
  url       = {https://www.kaspersky.ru/resource-center/definitions/what-is-cryptography},
  urldate   = {2024-04-15},
  language  = {russian},
  howpublished = {Электронный ресурс}
}

@book{schneier_applied_cryptography,
  title     = {Applied Cryptography: Protocols, Algorithms, and Source Code in C},
  author    = {Bruce Schneier},
  year      = {1996},
  edition   = {2nd},
  publisher = {John Wiley \& Sons},
  address   = {New York},
  isbn      = {978-0-471-11709-9},
  language  = {english}
}

@book{stallings_cryptography,
  title     = {Cryptography and Network Security: Principles and Practice},
  author    = {William Stallings},
  year      = {2017},
  edition   = {7th},
  publisher = {Pearson},
  address   = {Boston},
  isbn      = {978-0-13-444428-0},
  language  = {english}
}

@standard{gost_3412_2015,
  title  = {ГОСТ 34.12-2015. Информационная технология. Криптографическая защита информации. Блочные шифры},
  organization = {Федеральное агентство по техническому регулированию и метрологии},
  year   = {2015},
  address = {Москва},
  language = {russian}
}

@standard{gost_3411_2012,
  title  = {ГОСТ Р 34.11-2012. Информационная технология. Криптографическая защита информации. Функция хеширования},
  organization = {Федеральное агентство по техническому регулированию и метрологии},
  year   = {2012},
  address = {Москва},
  language = {russian}
}
